### ISSUE TITLE
Replace Google Analytics web property ID

### ISSUE THREAD

**Issue by jasonrudolph** [sanketparmar/sanketparmar.in#1]
@sanketparmar: It's cool to see http://sanketparmar.in/ using the layout and design from https://github.com/jasonrudolph/jasonrudolph.github.io. :+1:

Would you mind replacing the [Google Analytics web property ID](https://github.com/sanketparmar/sanketparmar.in/blob/bdc3d229687033a46ed87d7305d7ad99c672838b/javascripts/google_analytics.js#L6) with your own Google Analytics property ID for http://sanketparmar.in? Right now, it's using the [web property ID for jasonrudolph.com](https://github.com/jasonrudolph/jasonrudolph.github.io/blob/17024704a36df3cfcf06ab0aa315585e3d7e6fd6/javascripts/google_analytics.js#L6) (UA-4605088-1). Alternatively, if you're not using Google Analytics for your site, you could remove the `javascripts/google_analytics.js` file altogether.

**Comment by sanketparmar** [comment]
I am so sorry. I just missed that while porting. My bad.
I have removed the mentioned ID and will make sure that it will be reflected all other places.

Thanks!
Sanket

**Comment by jasonrudolph** [comment]
Thanks, @sanketparmar. Have you had a chance to deploy your change (https://github.com/sanketparmar/sanketparmar.in/commit/3180b697e9f64d32f97f14bb3f0c96704afa62cf)? It looks like sanketparmar.in is still using the web property ID for jasonrudolph.com:

```
$ curl http://sanketparmar.in/javascripts/google_analytics.js | grep UA-4605088-1

    var pageTracker = _gat._getTracker("UA-4605088-1");
```

**Comment by sanketparmar** [comment]
Yesterday I didn't get time to deploy the change. Today I did it. It is now using my id. To make sure, I also checked all files. 

Thanks!

**Comment by jasonrudolph** [comment]
Thanks, @sanketparmar. :bow:
